# Generated by Django 5.2.1 on 2025-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitnessapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
