# Generated by Django 5.2.2 on 2025-06-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitnessapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
    ]
