# Generated by Django 5.2.2 on 2025-06-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitnessapp', '0002_remove_users_is_active_remove_users_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 's_meals',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
