# Generated by Django 5.2.2 on 2025-06-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitnessapp', '0003_smeals_alter_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meals',
            name='meal_type',
            field=models.ForeignKey(db_column='meal_type', on_delete=django.db.models.deletion.DO_NOTHING, to='Fitnessapp.smeals'),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
