# Generated by Django 5.2.2 on 2025-06-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitnessapp', '0004_meals_is_deleted_alter_meals_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
