# Generated by Django 5.2.1 on 2025-06-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitnessapp', '0002_alter_trainings_creation_date'),
        ('Fitnessapp', '0005_alter_meals_creation_date'),
    ]

    operations = [
    ]
