# Generated by Django 5.2.1 on 2025-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitnessapp', '0006_merge_20250612_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='date',
            field=models.DateTimeField(default='2025-06-12 00:00:00.000000'),
            preserve_default=False,
        ),
    ]
